name: Linting the code

on:
  pull_request:
    branches: [ develop ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install nodejs
        working-directory: ./vanilla
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        working-directory: ./vanilla
        run: npm ci
      - name: Lint typescript
        working-directory: ./vanilla
        run: npm run lint
      - name: Lint styles
        working-directory: ./vanilla
        run: npm run stylelint